//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityBookingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingSystemDBEntities : DbContext
    {
        public BookingSystemDBEntities()
            : base("name=BookingSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblBookedDate> tblBookedDates { get; set; }
        public DbSet<tblBookedHall> tblBookedHalls { get; set; }
        public DbSet<tblBookedRequirement> tblBookedRequirements { get; set; }
        public DbSet<tblBookedSlot> tblBookedSlots { get; set; }
        public DbSet<tblBooking> tblBookings { get; set; }
        public DbSet<tblDepartment> tblDepartments { get; set; }
        public DbSet<tblHall> tblHalls { get; set; }
        public DbSet<tblPurpose> tblPurposes { get; set; }
        public DbSet<tblRequirement> tblRequirements { get; set; }
        public DbSet<tblRequirementForHall> tblRequirementForHalls { get; set; }
        public DbSet<tblSlot> tblSlots { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    }
}
