//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookedDate
    {
        public tblBookedDate()
        {
            this.tblBookedHalls = new HashSet<tblBookedHall>();
            this.tblBookedRequirements = new HashSet<tblBookedRequirement>();
            this.tblChairs = new HashSet<tblChair>();
        }
    
        public int dateID { get; set; }
        public Nullable<System.DateTime> dateChosen { get; set; }
        public Nullable<int> bookingID { get; set; }
        public Nullable<bool> nonWorkingHours { get; set; }
    
        public virtual tblBooking tblBooking { get; set; }
        public virtual ICollection<tblBookedHall> tblBookedHalls { get; set; }
        public virtual ICollection<tblBookedRequirement> tblBookedRequirements { get; set; }
        public virtual ICollection<tblChair> tblChairs { get; set; }
    }
}
