//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookedHall
    {
        public tblBookedHall()
        {
            this.tblBookedSlots = new HashSet<tblBookedSlot>();
        }
    
        public int bookedHallID { get; set; }
        public Nullable<int> hallID { get; set; }
        public Nullable<int> dateID { get; set; }
    
        public virtual tblBookedDate tblBookedDate { get; set; }
        public virtual ICollection<tblBookedSlot> tblBookedSlots { get; set; }
        public virtual tblHall tblHall { get; set; }
    }
}
