//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        public tblBooking()
        {
            this.tblBookedDates = new HashSet<tblBookedDate>();
            this.tblBookedRequirements = new HashSet<tblBookedRequirement>();
            this.tblChairs = new HashSet<tblChair>();
        }
    
        public int bookingID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> purposeID { get; set; }
        public string title { get; set; }
        public Nullable<bool> status { get; set; }
        public string bookingNo { get; set; }
        public Nullable<System.DateTime> bookedAtTime { get; set; }
    
        public virtual ICollection<tblBookedDate> tblBookedDates { get; set; }
        public virtual ICollection<tblBookedRequirement> tblBookedRequirements { get; set; }
        public virtual tblPurpose tblPurpose { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblChair> tblChairs { get; set; }
    }
}
