//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public tblDepartment()
        {
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int deptID { get; set; }
        public string department { get; set; }
    
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
