//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurpose
    {
        public tblPurpose()
        {
            this.tblBookings = new HashSet<tblBooking>();
        }
    
        public int purposeID { get; set; }
        public string purpose { get; set; }
    
        public virtual ICollection<tblBooking> tblBookings { get; set; }
    }
}
