//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityBookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSlot
    {
        public tblSlot()
        {
            this.tblBookedSlots = new HashSet<tblBookedSlot>();
        }
    
        public int slotID { get; set; }
        public string slot { get; set; }
    
        public virtual ICollection<tblBookedSlot> tblBookedSlots { get; set; }
    }
}
